export { default as NotFound} from './notFound/NotFound'
export { default as About} from './about/About'
export { default as Home} from './home/Home'
export { default as Product} from './product/Product'
export { default as Services} from './services/Services'
export { default as SignUp} from './signup/SignUp'